### ISSUE TITLE
2020-1 OSS mini project TOPIC

### ISSUE THREAD

**Issue by lhb0927** [lhb0927/2020OSS_miniproject#2]
2020 1학기 OSS mini project

**Comment by TaeyoungLee10** [comment]
어떤 항목을 관리할 CRUD 프로그램을 개발하면 좋을까요?

**Comment by TaeyoungLee10** [comment]
제가 지금 생각나는 것은:
1. 학생 성적 관리 프로그램
2. 예전에 mini project에서 했던 것처럼 과자 제품을 관리하는 프로그램
3. 아예 새로운 프로그램
이렇게 입니다

**Comment by lhb0927** [comment]
조금 바꿔서 카페 메뉴나 다른걸 적용해보면 어떨까요?

**Comment by TaeyoungLee10** [comment]
카페 메뉴 좋은 아이디어인거 같아요! 좋습니다!

**Comment by lhb0927** [comment]
도서관 열람시스템 같은 것도 좋을거 같네요!

**Comment by lhb0927** [comment]
어떤걸로 할까요?

**Comment by lhb0927** [comment]
카페 메뉴로 그럼 정하죠!

**Comment by TaeyoungLee10** [comment]
도서관 열람시스템이면 혹시 책 항목을 저장하는건가요?

**Comment by lhb0927** [comment]
네 그런걸 생각했었어요

**Comment by TaeyoungLee10** [comment]
아하~ 저는 둘다 좋을거 같긴한데 혹시 카페 메뉴 프로그램 괜찮으시면 그걸로 할까요?

**Comment by lhb0927** [comment]
네 그렇게해요~

**Comment by TaeyoungLee10** [comment]
좋습니다~
그러면 구조체를 먼저 정하고 어떤 기능함수들도 같이 구현할지 생각하면 좋을것 같습니다

**Comment by TaeyoungLee10** [comment]
우선 생각나는 것들은 이런 항목입니다: 
메뉴 이름
가격
사이즈
ice/hot

**Comment by lhb0927** [comment]
카톡 한번 확인해 주세요~
